project:
  type: website
  output-dir: docs

website:
  title: "watershed-fires-comm"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda_text.qmd
        text: Exploratory Data Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



